- name: Deploy RustFS
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - rustFS
  tags:
    - rustfs

- name: Deploy InfluxDB
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - observability/influxDB
  tags:
    - influxdb
    - observability

- name: Deploy Telegraf
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - observability/telegraf-docker
  tags:
    - telegraf-docker
    - observability

- name: Deploy GitLab
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - gitlab/gitlab-omnibus
  tags:
    - gitlab
    - omnibus

- name: Deploy GitLab Runner
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - gitlab/gitlab-runner
  tags:
    - gitlab
    - runner

- name: Deploy Jitsi
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - jitsi
  tags:
    - jitsi
- name: Deploy Confluence
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - confluence
  tags:
    - confluence

- name: Setup System Role
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - setup/system-setup
  tags:
    - system-setup

- name: Install and configure kubectl
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - kubectl
  tags:
    - kubectl

- name: Install and configure kind
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - kind
  tags:
    - kind

- name: Install and configure minikube
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - minikube
  tags:
    - minikube

- name: Install, configure, and create k3d cluster
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - k3d
  tags:
    - k3d
