#!/usr/bin/env python3
"""Offline tests of opt-in semantics, configuration merging and rollback behavior."""
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch
import yaml
from jinja2 import Environment, FileSystemLoader

ROLE = Path(__file__).resolve().parents[1]

def load(name):
    spec = importlib.util.spec_from_file_location(name, ROLE / 'library' / (name + '.py'))
    result = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(result)
    return result

transaction = load('linux_hardening_transaction')
validator = load('linux_hardening_validate')
moduli = load('linux_hardening_moduli')
DEFAULTS = yaml.safe_load((ROLE / 'defaults/main.yml').read_text())
SNAPSHOT = '''# Generated by iptables-save
*filter
:INPUT ACCEPT [24:4800]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:DOCKER - [0:0]
-A INPUT -s 192.0.2.0/24 -j ACCEPT
-A FORWARD -j DOCKER
COMMIT
'''

class Controls(unittest.TestCase):
    def test_defaults_all_opt_in(self):
        validator.validate(DEFAULTS)
        def walk(value):
            if isinstance(value, dict):
                for key, child in value.items():
                    if isinstance(child, bool):
                        self.assertIs(child, False, key)
                    walk(child)
            elif isinstance(value, list):
                for child in value:
                    walk(child)
        walk(DEFAULTS)

    def test_string_true_rejected(self):
        for value in ('true', 'false', 1, None):
            with self.assertRaises(ValueError):
                validator.validate(DEFAULTS | {'iptables_hardening_enabled': value})

    def test_nested_string_true_rejected(self):
        with self.assertRaises(ValueError):
            validator.validate(DEFAULTS | {'ssh_hardening_server_directives': {
                'PasswordAuthentication': {'enabled': 'true', 'value': 'no'}}})

    def test_disabled_lists_do_not_generate_rules(self):
        env = Environment(loader=FileSystemLoader(ROLE / 'templates'))
        for template in ('iptables.rules.j2', 'ip6tables.rules.j2'):
            text = env.get_template(template).render(DEFAULTS | {'iptables_hardening_tcp_ports': [80,443]})
            self.assertNotIn('-A ', text)
            self.assertEqual(transaction.canonical_rules(SNAPSHOT),
                             transaction.canonical_rules(transaction.merge_rules(SNAPSHOT, text, {})))

    def test_firewall_foreign_rules_and_disabled_controls_retained(self):
        old = SNAPSHOT.replace('COMMIT', '-A INPUT -m comment --comment "linux-hardening:custom_tcp" -p tcp --dport 443 -j ACCEPT\nCOMMIT')
        fragment = '# control:allow_ssh\n-A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -j ACCEPT\n'
        new = transaction.merge_rules(old, fragment, {'INPUT': {'enabled': True, 'value': 'DROP'},
                                                     'OUTPUT': {'enabled': False, 'value': 'DROP'}})
        self.assertIn(':INPUT DROP', new)
        self.assertIn(':OUTPUT ACCEPT', new)
        self.assertIn('-A FORWARD -j DOCKER', new)
        self.assertIn('--dport 443', new)
        self.assertEqual(new, transaction.merge_rules(new, fragment, {'INPUT': {'enabled': True, 'value': 'DROP'}}))

    def test_enabled_empty_port_group_removes_only_its_rules(self):
        old = SNAPSHOT.replace('COMMIT', '-A INPUT -m comment --comment "linux-hardening:custom_tcp" -p tcp --dport 443 -j ACCEPT\nCOMMIT')
        new = transaction.merge_rules(old, '# control:custom_tcp\n', {})
        self.assertNotIn('--dport 443', new)
        self.assertIn('192.0.2.0/24', new)

    def test_iptables_save_normalization_is_idempotent(self):
        generated = '-A INPUT -m comment --comment "linux-hardening:allow_ssh" -p tcp --dport 22 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT\n'
        saved = '-A INPUT -p tcp -m comment --comment linux-hardening:allow_ssh -m tcp --dport 22 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT\n'
        self.assertEqual(transaction.canonical_rules(generated), transaction.canonical_rules(saved))

    def test_empty_nft_compatibility_backend_has_recoverable_accept_baseline(self):
        with patch.object(transaction, 'run', return_value=''):
            snapshot = transaction.firewall_snapshot('iptables')
        self.assertEqual(snapshot, transaction.EMPTY_FILTER)
        new = transaction.merge_rules(snapshot, '', {'INPUT': {'enabled': True, 'value': 'DROP'}})
        self.assertIn(':INPUT DROP', new)
        self.assertIn(':OUTPUT ACCEPT', new)

    def test_default_log_level_normalization(self):
        generated = '-A INPUT -m comment --comment "linux-hardening:log_dropped" -j LOG --log-prefix "lh-input: " --log-level 4\n'
        saved = '-A INPUT -m comment --comment linux-hardening:log_dropped -j LOG --log-prefix "lh-input: "\n'
        self.assertEqual(transaction.canonical_rules(generated), transaction.canonical_rules(saved))

    def test_firewall_chain_grouping_preserves_per_chain_order(self):
        env = Environment(loader=FileSystemLoader(ROLE / 'templates'))
        values = DEFAULTS | {'iptables_hardening_drop_invalid': True,
                             'iptables_hardening_allow_established': True,
                             'iptables_hardening_allow_loopback': True}
        for template in ('iptables.rules.j2', 'ip6tables.rules.j2'):
            desired = transaction.merge_rules(SNAPSHOT, env.get_template(template).render(values), {})
            lines = desired.splitlines()
            rules = [line for line in lines if line.startswith('-A ')]
            grouped = sorted(rules, key=lambda line: line.split()[1])
            prefix = [line for line in lines if line != 'COMMIT' and not line.startswith('-A ')]
            saved = '\n'.join(prefix + grouped + ['COMMIT']) + '\n'
            self.assertEqual(transaction.canonical_rules(desired), transaction.canonical_rules(saved))
            reordered = '\n'.join(prefix + list(reversed(grouped)) + ['COMMIT']) + '\n'
            self.assertNotEqual(transaction.canonical_rules(desired), transaction.canonical_rules(reordered))

    def test_commit_accepts_chain_grouping_but_rejects_rule_changes(self):
        rules = ['-A INPUT -j ACCEPT', '-A OUTPUT -j ACCEPT', '-A INPUT -j DROP']
        desired = transaction.EMPTY_FILTER.replace('COMMIT', '\n'.join(rules) + '\nCOMMIT')
        saved = transaction.EMPTY_FILTER.replace('COMMIT', '\n'.join([rules[0], rules[2], rules[1]]) + '\nCOMMIT')
        for changed in (False, True):
            with self.subTest(changed=changed), tempfile.TemporaryDirectory() as temp:
                state = Path(temp) / 'state'
                state.mkdir()
                info = {'token': 'a'*32, 'desired_files': {},
                        'desired_firewall': {'iptables': desired}, 'persistent': False}
                (state / 'state.json').write_text(json.dumps(info))
                (state / 'pending').touch()
                actual = saved.replace('-A INPUT -j DROP', '-A INPUT -j REJECT') if changed else saved
                with patch.object(transaction, 'state_root', return_value=state), \
                     patch.object(transaction, 'firewall_snapshot', return_value=actual), \
                     patch.object(transaction, 'run') as command:
                    if changed:
                        with self.assertRaisesRegex(ValueError, 'Concurrent firewall change'):
                            transaction.commit('firewall', 'a'*32)
                        self.assertTrue((state / 'pending').exists())
                        command.assert_not_called()
                    else:
                        transaction.commit('firewall', 'a'*32)
                        self.assertFalse(state.exists())
                        command.assert_called_once_with(['systemctl', 'stop', 'linux-hardening-' + 'a'*32 + '.timer'])

    def test_ipv4_ipv6_rule_parity(self):
        env = Environment(loader=FileSystemLoader(ROLE / 'templates'))
        enabled = {key: True for key in validator.BOOLEAN_NAMES if key.startswith('iptables_hardening_')}
        values = DEFAULTS | enabled
        v4 = env.get_template('iptables.rules.j2').render(values)
        v6 = env.get_template('ip6tables.rules.j2').render(values)
        self.assertEqual(v4.count('-A '), v6.count('-A '))
        self.assertIn('-p ipv6-icmp', v6)
        self.assertIn('-p icmp', v4)
        self.assertIn('::1/128', v6)
        self.assertIn('127.0.0.0/8', v4)

    def test_ssh_includes_and_disabled_directive_preservation(self):
        with tempfile.TemporaryDirectory() as temp:
            root, drop = Path(temp)/'sshd_config', Path(temp)/'cloud.conf'
            root.write_text(f'Include {drop}\nPasswordAuthentication yes\nMatch User backup\n PasswordAuthentication yes\n')
            drop.write_text('PermitRootLogin yes\nPasswordAuthentication yes\n')
            selected = {'PermitRootLogin': {'enabled': True,'value':'no'},
                        'PasswordAuthentication': {'enabled': False,'value':'no'}}
            old, new, _ = transaction.ssh_candidates(str(root), selected, [])
            self.assertIn('PasswordAuthentication yes',new[str(drop)])
            self.assertIn('Match User backup\n PasswordAuthentication yes',new[str(root)])
            self.assertTrue(new[str(root)].startswith('PermitRootLogin no\n'))
            for path, value in new.items(): Path(path).write_text(value)
            _, again, _ = transaction.ssh_candidates(str(root),selected,[])
            self.assertEqual(again,new)

    def test_ssh_alias_removed_only_when_control_enabled(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp)/'sshd_config'
            root.write_text('ChallengeResponseAuthentication yes\n')
            _,new,_=transaction.ssh_candidates(str(root),{'KbdInteractiveAuthentication':{'enabled':True,'value':'no'}},[])
            self.assertNotIn('ChallengeResponse',new[str(root)])

    def test_ssh_scope_disabled_rule_preserved(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp)/'sshd_config'
            root.write_text('Port 22\n')
            scope={'id':'backup','enabled':True,'match':'User backup','directives':{
                'AllowTcpForwarding':{'enabled':True,'value':'no'},
                'X11Forwarding':{'enabled':True,'value':'no'}}}
            _,new,_=transaction.ssh_candidates(str(root),{},[scope])
            root.write_text(new[str(root)])
            scope['directives']['X11Forwarding']['enabled']=False
            scope['directives']['AllowTcpForwarding']['value']='local'
            _,again,_=transaction.ssh_candidates(str(root),{},[scope])
            self.assertIn('  X11Forwarding no',again[str(root)])
            self.assertIn('  AllowTcpForwarding local',again[str(root)])

    def test_client_host_exceptions_precede_global_defaults(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp)/'ssh_config'
            root.write_text('Host special\n  Port 2222\nHost *\n  Port 22\n  Compression yes\n')
            controls={'Port':{'enabled':True,'value':'2223'},'Compression':{'enabled':False,'value':'no'}}
            _,new,_=transaction.ssh_candidates(str(root),controls,[],True)
            root.write_text(new[str(root)])
            _,again,_=transaction.ssh_candidates(str(root),controls,[],True)
            self.assertEqual(new,again)
            for host,port in [('special','2222'),('other','2223')]:
                result=subprocess.run(['ssh','-G','-F',str(root),host],capture_output=True,text=True,check=True)
                self.assertIn('port '+port+'\n',result.stdout)
                self.assertIn('compression yes\n',result.stdout)

    def test_native_sshd_validates_all_nonempty_default_directives(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp)/'sshd_config';key=Path(temp)/'host_key'
            subprocess.run(['ssh-keygen','-q','-t','ed25519','-N','','-f',str(key)],check=True)
            root.write_text('HostKey '+str(key)+'\n')
            options={key:dict(value=value['value'],enabled=True)
                     for key,value in DEFAULTS['ssh_hardening_server_directives'].items()
                     if value['value'] and key not in ('HostKey','HostCertificate','TrustedUserCAKeys','RevokedKeys')}
            _,contents,includes=transaction.ssh_candidates(str(root),options,[])
            transaction.validate_ssh(str(root),contents,includes,False)

    def test_native_sshd_rejects_bad_candidate_without_changing_original(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp)/'sshd_config';key=Path(temp)/'host_key'
            subprocess.run(['ssh-keygen','-q','-t','ed25519','-N','','-f',str(key)],check=True)
            original='HostKey '+str(key)+'\n'
            root.write_text(original)
            _,contents,includes=transaction.ssh_candidates(str(root),{'Port':{'enabled':True,'value':'99999'}},[])
            with self.assertRaises(RuntimeError): transaction.validate_ssh(str(root),contents,includes,False)
            self.assertEqual(root.read_text(),original)

    def test_ssh_directive_newline_injection_rejected(self):
        with self.assertRaises(ValueError):
            transaction.directive_lines({'Port':{'enabled':True,'value':'22\nPermitRootLogin yes'}})

    def test_recursive_include_rejected(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp)/'sshd_config'
            root.write_text('Include '+str(root)+'\n')
            with self.assertRaises(ValueError):
                transaction.ssh_candidates(str(root),{},[])

    def test_moduli_keeps_2048_bit_groups_and_refuses_empty_result(self):
        text='# Comment\n0 2 6 100 2047 2 AA\n0 2 6 100 1023 2 BB\n'
        self.assertEqual(moduli.filter_moduli(text,2048),'# Comment\n0 2 6 100 2047 2 AA\n')
        with self.assertRaises(ValueError): moduli.filter_moduli(text,4096)

    def test_watchdog_restores_files_and_marks_transaction_expired(self):
        with tempfile.TemporaryDirectory() as temp:
            state=Path(temp)/'state';state.mkdir()
            target=Path(temp)/'config';target.write_text('new')
            (state/'state.json').write_text(json.dumps({'kind':'client','files':{str(target):{
                'content':'old','mode':0o600,'uid':os.getuid(),'gid':os.getgid()}},'firewall':{}}))
            (state/'pending').touch()
            result=subprocess.run(['python3','-c',transaction.WATCHDOG,str(state)],capture_output=True,text=True)
            self.assertEqual(result.returncode,0,result.stderr)
            self.assertEqual(target.read_text(),'old')
            self.assertTrue((state/'rolled-back').exists())
            self.assertFalse((state/'pending').exists())

    def test_commit_rejects_expired_or_foreign_token(self):
        with tempfile.TemporaryDirectory() as temp, patch.object(transaction,'state_root',return_value=Path(temp)):
            (Path(temp)/'state.json').write_text(json.dumps({'token':'a'*32}))
            with self.assertRaises(ValueError): transaction.commit('server','a'*32)
            (Path(temp)/'pending').touch()
            with self.assertRaises(ValueError): transaction.commit('server','b'*32)

    def test_commit_persists_only_selected_family_after_runtime_validation(self):
        with tempfile.TemporaryDirectory() as temp:
            state=Path(temp)/'state';state.mkdir()
            output=Path(temp)/'rules.v4';output.write_text('old persistence')
            info={'token':'a'*32,'kind':'firewall','files':{},'firewall':{'iptables':SNAPSHOT},
                  'desired_files':{},'desired_firewall':{'iptables':SNAPSHOT},'persistent':True}
            (state/'state.json').write_text(json.dumps(info));(state/'pending').touch()
            calls=[]
            def command(argv,data=None):
                calls.append(argv)
                return SNAPSHOT if argv[0]=='iptables-save' else ''
            with patch.object(transaction,'state_root',return_value=state), \
                 patch.object(transaction,'persistence_path',return_value=output), \
                 patch.object(transaction,'run',side_effect=command), \
                 patch.object(transaction.os,'chown'):
                transaction.commit('firewall','a'*32)
            self.assertEqual(output.read_text(),SNAPSHOT)
            self.assertFalse(state.exists())
            self.assertFalse(any('ip6tables' in argv[0] for argv in calls))
            self.assertIn(['iptables-restore','--test','--wait','10'],calls)

    def test_persistence_failure_keeps_rollback_armed_and_original_journaled(self):
        with tempfile.TemporaryDirectory() as temp:
            state=Path(temp)/'state';state.mkdir()
            output=Path(temp)/'rules.v4';output.write_text('old persistence')
            info={'token':'a'*32,'kind':'firewall','files':{},'firewall':{'iptables':SNAPSHOT},
                  'desired_files':{},'desired_firewall':{'iptables':SNAPSHOT},'persistent':True}
            (state/'state.json').write_text(json.dumps(info));(state/'pending').touch()
            real_atomic=transaction.atomic
            def write(path,data,metadata=None):
                if Path(path)==output:
                    raise OSError('Simulated full filesystem')
                real_atomic(path,data,metadata)
            with patch.object(transaction,'state_root',return_value=state), \
                 patch.object(transaction,'persistence_path',return_value=output), \
                 patch.object(transaction,'run',side_effect=lambda argv,data=None: SNAPSHOT if argv[0]=='iptables-save' else ''), \
                 patch.object(transaction,'atomic',side_effect=write), \
                 patch.object(transaction.os,'chown'):
                with self.assertRaises(OSError): transaction.commit('firewall','a'*32)
            self.assertEqual(output.read_text(),'old persistence')
            self.assertTrue((state/'pending').exists())
            journal=json.loads((state/'state.json').read_text())
            self.assertEqual(journal['files'][str(output)]['content'],'old persistence')

    def test_second_family_apply_failure_invokes_rollback_without_persistence(self):
        with tempfile.TemporaryDirectory() as temp:
            state=Path(temp)/'state'
            calls=[]
            def command(argv,data=None):
                calls.append(argv)
                if argv[0].endswith('-save'): return SNAPSHOT
                if argv[0]=='ip6tables-restore': raise RuntimeError('Simulated second-family failure')
                return ''
            proposed=transaction.merge_rules(SNAPSHOT,'',{'INPUT':{'enabled':True,'value':'DROP'}})
            with patch.object(transaction,'state_root',return_value=state), \
                 patch.object(transaction,'run',side_effect=command), \
                 patch.object(transaction.subprocess,'run') as watchdog:
                with self.assertRaises(RuntimeError):
                    transaction.apply_transaction('firewall',{}, {},
                        {'iptables':SNAPSHOT,'ip6tables':SNAPSHOT},
                        {'iptables':proposed,'ip6tables':proposed},True,180)
            watchdog.assert_called_once()
            self.assertIn('rollback.py',watchdog.call_args.args[0][1])
            self.assertFalse(any(argv==['iptables-save'] for argv in calls))

if __name__=='__main__': unittest.main(verbosity=2)
