all:
  children:
    rustfs:
      hosts:
        rustfs-arvan:
          ansible_host: 127.0.0.1
          ansible_connection: local

    elasticsearch:
      hosts:
        elasticsearch-arvan:
          ansible_host: 127.0.0.1
          ansible_connection: local

    logstash:
      hosts:
        logstash-arvan:
          ansible_host: 127.0.0.1
          ansible_connection: local
    
    kibana:
      hosts:
        kibana-arvan:
          ansible_host: 127.0.0.1
          ansible_connection: local

    fleet:
      hosts:
        fleet-arvan:
          ansible_host: 127.0.0.1
          ansible_connection: local
      
    agent:
      hosts:
        agent-arvan:
          ansible_host: 127.0.0.1
          ansible_connection: local

    traefik:
      hosts:
        traefik-arvan:
          ansible_host: 127.0.0.1
          ansible_connection: local

    local-mizban:
      hosts:
        alch-hp:
          ansible_host: 127.0.0.1
          ansible_connection: local
