---
- name: Setup confluence Service
  ansible.builtin.import_tasks: confluence-setup.yml
  tags:
    - setup_confluence

- name: Activate confluence service
  ansible.builtin.import_tasks: confluence-activate.yml
  tags:
    - activate_confluence

- name: Set cronjob for Confluence backup sync
  ansible.builtin.import_tasks: confluence-backup-sync.yml
  when: confluence_remote_backup_enabled | bool
  tags:
    - backup
    - cron
