[INCLUDES]
before = common.conf

[Definition]
_daemon = pvedaemon
failregex = ^%(__prefix_line)sauthentication failure; rhost=<HOST> user=\S+ msg=.*$
ignoreregex =
journalmatch = _SYSTEMD_UNIT=pvedaemon.service
