---
all:
  children:
    respina:
      hosts:
        mattermost:
          ansible_host: 77.237.70.36
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        confluence:
          ansible_host: 77.237.70.196
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        jira:
          ansible_host: 77.237.70.196
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        gitlab:
          ansible_host: 77.237.70.194
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        runner:
          ansible_host: 172.16.154.6
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        postgres-master:
          ansible_host: 77.237.70.38
          ansible_user: debian
          ansible_port: 22
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        postgres-slave:
          ansible_host: 172.16.154.29
          ansible_user: debian
          ansible_port: 22
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
        
        jitsi:
          ansible_host: 77.237.70.36
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        prometheus:
          ansible_host: 172.16.154.20
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        alertmanager:
          ansible_host: 172.16.154.20
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        grafana:
          ansible_host: 172.16.154.21
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rs
        
        loki:
          ansible_host: 77.237.70.38
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        mimir:
          ansible_host: 172.16.154.22
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        core-stage:
          ansible_host: 77.237.70.43
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          container_bind_ip: 77.237.70.43
          promtail_label: Core-Stage-Respina

        sentry:
          ansible_host: 77.237.70.37
          ansible_user: root
          ansible_port: 9510
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          exporters_node_exporter_bind_ip: "172.16.154.25"

        clean-server:
          ansible_host: 77.237.70.39
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          exporters_node_exporter_bind_ip: "172.16.154.13"

        core-prod:
          ansible_host: 77.237.70.42
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          exporters_node_exporter_bind_ip: "172.16.154.70"

        panel-stage:
          ansible_host: 77.237.70.44
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          exporters_node_exporter_bind_ip: "172.16.154.26"

        panel-prod:
          ansible_host: 77.237.70.45
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          exporters_node_exporter_bind_ip: "172.16.154.27"

        repo:
          ansible_host: 77.237.70.197
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          exporters_node_exporter_bind_ip: "172.16.154.7"
          
        mqtt:
          ansible_host: 77.237.70.195
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          cadvisor_exporter_bind_ip: "172.16.154.8"

    arvan:
      hosts:
        nginx-cic:
          ansible_host: 37.32.12.209
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          exporters_node_exporter_bind_ip: "127.0.0.1"

        nginx-cip:
          ansible_host: 94.101.177.209
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
          exporters_node_exporter_bind_ip: "127.0.0.1"

        waggy-back-stage:
          ansible_host: 188.121.100.63
          ansible_user: debian
          ansible_port: 22
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
        
        veritariff:
          ansible_host: 94.101.185.122
          ansible_user: debian
          ansible_port: 22
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa

        devops-stage:
          ansible_host: 188.121.103.200
          ansible_user: debian
          ansible_port: 4578
          ansible_ssh_private_key_file: /home/ali/.ssh/id_rsa
