---
galaxy_info:
  role_name: mikrotik_l2tp_server
  author: Ali Kalbasi
  description: Create missing RouterOS L2TP resources and configure an IPsec-required server
  license: Apache-2.0
  min_ansible_version: '2.15'
dependencies: []
